### ISSUE TITLE
Parameters should depend on analysis

### ISSUE THREAD

**Issue by bendichter** [scratchrealm/neurobass#10]
<img width="558" alt="image" src="https://github.com/scratchrealm/neurobass/assets/844306/61dddb3d-4225-41c1-bda6-88f4fadbd910">

Right now there is just a single parameter, ElectricalSeries path. We will be supporting processes that have many possible parameters. We should make the parameters fields dynamic, changing based on what analysis is selected

**Comment by magland** [comment]
Yes, it will be dynamic. As noted in other issue "this dialog is obsolete and has been removed in my latest deploy"
