### ISSUE TITLE
ElectricalSeries path should auto-populate

### ISSUE THREAD

**Issue by bendichter** [scratchrealm/neurobass#11]
<img width="558" alt="image" src="https://github.com/scratchrealm/neurobass/assets/844306/6c18ba51-a021-4bc0-b31b-52ea26a091aa">

The program should be able to detect if there is a single ElectricalSeries in the NWB file and automatically populate it. If there is more than one ElectricalSeries, it should provide a dropdown

**Comment by magland** [comment]
I agree. That will involve utilizing code from neurosift for reading the remote nwb file.

Note that this dialog is obsolete and has been removed in my latest deploy, but I will keep this issue open anyway.

**Comment by bendichter** [comment]
It looks like this is done: 
<img width="849" alt="image" src="https://github.com/scratchrealm/neurobass/assets/844306/2793e577-b94d-4360-b24c-30a8f4baad35">
