### ISSUE TITLE
add ability to remove dataset

### ISSUE THREAD

**Issue by bendichter** [scratchrealm/neurobass#17]
<img width="1727" alt="image" src="https://github.com/scratchrealm/neurobass/assets/844306/58b03262-3729-4cbe-b3f4-d385d06e683c">

I don't see a way to remove a dataset from the project

**Comment by magland** [comment]
This is done

![image](https://github.com/scratchrealm/neurobass/assets/3679296/95398290-650a-4c0f-bacb-f874ec69339f)
