### ISSUE TITLE
Better integration with DANDI

### ISSUE THREAD

**Issue by bendichter** [scratchrealm/neurobass#3]
It would be good to use the [DANDI REST API](https://dandi.readme.io/reference) to query dandisets and the folder structure of the dandiset.

**Comment by magland** [comment]
This is now working to an extent

![image](https://github.com/scratchrealm/neurobass/assets/3679296/835490f6-e4c1-41d1-a907-30ba96711ca3)

**Comment by magland** [comment]
The file import has been improved. Here's a screenshot of the new interface

![image](https://github.com/scratchrealm/neurobass/assets/3679296/f326fb30-c087-49e0-89e7-69bd19ea7169)

It has search capability. The imported file name matches the DANDI path, as you requested. The main limitation is that you can still only import one file at a time. I'm thinking about how to support batch import.
