### ISSUE TITLE
show size of files

### ISSUE THREAD

**Issue by bendichter** [scratchrealm/neurobass#36]
Could you show the size of the files? I know we aren't actually storing the source files in the app, so they aren't taking up space, but it's still useful to know how many GBs they are so you have a sense for how long it will probably take to spike sort

<img width="1726" alt="image" src="https://github.com/scratchrealm/neurobass/assets/844306/dfb5c906-9c33-4813-9200-e29613dd5e78">

**Comment by magland** [comment]
This is done.
