### ISSUE TITLE
analysis should be dropdown

### ISSUE THREAD

**Issue by bendichter** [scratchrealm/neurobass#9]
<img width="558" alt="image" src="https://github.com/scratchrealm/neurobass/assets/844306/27ba1eec-6df7-4830-bbca-4bea560428f5">

analysis is a free string right now. Would it be possible to change this to a dropdown of all available analyses?

**Comment by magland** [comment]
That dialog is obsolete and has been removed in my latest deploy. The new method is to click on the imported NWB file and then click "Run spike sorting". At that point there is a dropdown to select the sorter.

**Comment by bendichter** [comment]
Have you deployed the latest version? I still see the .nba interface

<img width="862" alt="image" src="https://github.com/scratchrealm/neurobass/assets/844306/09a6bcea-d573-4b13-b579-fbd1aa3969e7">

**Comment by magland** [comment]
> Have you deployed the latest version? I still see the .nba interface

Yes, the .nba file is a text file that is still in the project. But if you click on it you will only see the contents of the text file, not that dialog. The "Create analysis" button has disappeared, so no new .nba files will be created. You can right-click to delete it.

**Comment by bendichter** [comment]
This is true for new projects. Old workspaces still have that button. I'll delete my old projects so I only see the new interface
